export type Language = 'zh' | 'en'

type Dict = Record<string, Record<Language, string>>

export const dict: Dict = {
  appTitle: { zh: '人格特质投资策略评估系统', en: 'Personality Investment Strategy Assessment' },
  appDesc: { zh: '使用账号密码登录，开始您的投资性格评估', en: 'Login to start your investment personality assessment' },
  emailLabel: { zh: '邮箱地址', en: 'Email Address' },
  emailPlaceholder: { zh: '请输入您的邮箱', en: 'Enter your email' },
  passwordLabel: { zh: '密码', en: 'Password' },
  passwordLabelSet: { zh: '设置密码', en: 'Set Password' },
  passwordPlaceholder: { zh: '请输入密码', en: 'Enter password' },
  passwordPlaceholderSet: { zh: '至少6位', en: 'At least 6 characters' },
  copyOkTitle: { zh: '已复制到粘贴板', en: 'Copied to clipboard' },
  copyOkDesc: { zh: '账号与密码已复制，请妥善保存', en: 'Your account and password are copied, please keep them safe' },
  registerOkTitle: { zh: '注册成功', en: 'Registration successful' },
  registerOkDesc: { zh: '请妥善保存密码，系统不提供找回；请使用账号密码登录', en: 'Please keep your password safe; password recovery is not available. Use email/password to login.' },
  registerFailTitle: { zh: '注册失败', en: 'Registration failed' },
  loginOkTitle: { zh: '登录成功', en: 'Login successful' },
  loginOkDescUser: { zh: '欢迎使用人格特质投资策略评估系统', en: 'Welcome to the assessment system' },
  loginOkDescAdmin: { zh: '欢迎管理员！', en: 'Welcome, admin!' },
  loginFailTitle: { zh: '登录失败', en: 'Login failed' },
  emailInvalidTitle: { zh: '邮箱格式错误', en: 'Invalid email format' },
  emailInvalidDesc: { zh: '请输入有效的邮箱地址', en: 'Please enter a valid email address' },
  deepseekTitle: { zh: 'DeepSeek AI 专业分析', en: 'DeepSeek AI Professional Analysis' },
  deepseekDesc: { zh: '基于您的测评数据，由 DeepSeek AI 生成的个性化投资心理分析报告', en: 'Personalized investment psychology analysis generated by DeepSeek AI based on your assessment data' },
  saveLocal: { zh: '保存本地', en: 'Save locally' },
  downloadJSON: { zh: '下载JSON', en: 'Download JSON' },
  deepDiveBadge: { zh: '深度解读', en: 'Deep Dive' },
  poweredBy: { zh: 'Powered by DeepSeek AI', en: 'Powered by DeepSeek AI' },
  generatedAt: { zh: '生成时间：', en: 'Generated at: ' },
}

